name: Continuos Integration

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create env variables
        run: |
          echo SENDIU_USERNAME=${{ secrets.SENDIU_USERNAME }} >> .env
          echo SENDIU_PASSWORD=${{ secrets.SENDIU_PASSWORD }} >> .env

      - name: Run tests
        run: npm run test
